patterns:
- pattern:
    confidence: high
    name: 姓名
    regex: ^[\u4e00-\u9fff]{2,4}$
- pattern:
    confidence: high
    name: 身份证号
    regex: ^[1-9]\d{5}(18|19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-2]\d|3[0-1])\d{3}[\dXx]$
- pattern:
    confidence: high
    name: 护照号
    regex: ^[A-Za-z]\d{8}$
- pattern:
    confidence: high
    name: 户籍地址
    regex: ^[\u4e00-\u9fffA-Za-z0-9\-·]+省?[\u4e00-\u9fffA-Za-z0-9\-·]+(市|区|县|镇|乡|村)[\d号]*$
- pattern:
    confidence: high
    name: 手机号
    regex: ^1[3-9]\d{9}$
- pattern:
    confidence: high
    name: 电子邮箱
    regex: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
- pattern:
    confidence: high
    name: SIM卡号
    regex: ^\d{19}$
- pattern:
    confidence: high
    name: 银行账户
    regex: ^[1-9]\d{15,18}$
- pattern:
    confidence: high
    name: 信用卡号
    regex: ^(4\d{12}(\d{3})?|5[1-5]\d{14}|3[47]\d{13}|6(?:011|5\d{2})\d{12})$
- pattern:
    confidence: high
    name: 病历
    regex: (病历|病史)[:：]\s*[\u4e00-\u9fffA-Za-z0-9]+
- pattern:
    confidence: high
    name: 诊断报告
    regex: 诊断[:：]\s*[A-Z]\d{2}\.\d{1}(\s*[\u4e00-\u9fff]+)?
- pattern:
    confidence: high
    name: 药物使用记录
    regex: (用药|处方)[:：]\s*[\u4e00-\u9fffA-Za-z0-9]+(\(\d+mg|\d+片/日\))?
- pattern:
    confidence: high
    name: GPS坐标
    regex: ^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$
- pattern:
    confidence: high
    name: 出行记录
    regex: (\d{4}-\d{2}-\d{2}\s+(航班|高铁)\s+[A-Z0-9]+)
- pattern:
    confidence: high
    name: 学籍号
    regex: ^G\d{4}[A-Za-z0-9]{6,8}$
- pattern:
    confidence: high
    name: 成绩单
    regex: (科目|成绩)[:：]\s*[\u4e00-\u9fff]+\s*[A-F0-9]{1,3}分?
- pattern:
    confidence: high
    name: 学位证书编号
    regex: ^[A-Za-z0-9]{12}$
- pattern:
    confidence: high
    name: 社保账号
    regex: ^\d{10,12}$
- pattern:
    confidence: high
    name: 工资单
    regex: 工资[:：]\s*\d+(\.\d{2})?元
- pattern:
    confidence: high
    name: 劳动合同编号
    regex: ^HT-[A-Z0-9]{8}$
- pattern:
    confidence: high
    name: IP地址
    regex: ^((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)$
- pattern:
    confidence: high
    name: 加密货币钱包地址
    regex: ^0x[a-fA-F0-9]{40}$
- pattern:
    confidence: high
    name: MAC地址
    regex: ^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$
- pattern:
    confidence: high
    name: 浏览历史URL
    regex: URL[:：]\s*(http|https)://[a-zA-Z0-9./?=_-]+
- pattern:
    confidence: high
    name: Token
    regex: Bearer\s+[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+\.[A-Za-z0-9\-_]+ 